# Generated by Django 5.2.17 on 2026-10-08 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termsacceptance',
            name='document',
            field=models.CharField(choices=[('terms', 'Terms'), ('privacy', 'Privacy notice'), ('aup', 'Acceptable use'), ('privacy_shown', 'Privacy notice shown (not accepted)')], max_length=16),
        ),
    ]
