# Generated by Django 5.2.17 on 2026-10-06 10:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=64)),
                ('max_domains', models.PositiveIntegerField()),
                ('max_mailboxes_per_domain', models.PositiveIntegerField()),
                ('mailbox_quota_mb', models.PositiveIntegerField()),
                ('daily_send_limit', models.PositiveIntegerField()),
                ('price_try_monthly', models.PositiveIntegerField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('prefix', models.CharField(max_length=8, unique=True)),
                ('key_hash', models.CharField(max_length=64)),
                ('scopes', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_label', models.CharField(blank=True, max_length=254)),
                ('action', models.CharField(db_index=True, max_length=48)),
                ('object_type', models.CharField(max_length=24)),
                ('object_ref', models.CharField(max_length=320)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=253, unique=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('verified', 'verified'), ('suspended', 'suspended')], default='pending', max_length=12)),
                ('verification_token', models.CharField(blank=True, editable=False, max_length=64)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_check_at', models.DateTimeField(blank=True, null=True)),
                ('last_check', models.JSONField(blank=True, default=dict)),
                ('dkim_selector', models.CharField(default='posta', max_length=32)),
                ('dkim_txt', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mailbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_part', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=320, unique=True)),
                ('quota_mb', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('active', 'active'), ('suspended', 'suspended')], default='active', max_length=12)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailboxes', to='hosting.domain')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'active'), ('suspended', 'suspended')], default='active', max_length=12)),
                ('since', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hosting.plan')),
            ],
        ),
    ]
